amap:
    type: rest
    resource: "@AppBundle/Controller/AmapsController.php"
    name_prefix:  api_
    options:
        expose: true

produit:
    type: rest
    resource: "@AppBundle/Controller/ProduitsController.php"
    name_prefix:  api_
    options:
        expose: true

producteur:
    type: rest
    resource: "@AppBundle/Controller/ProducteursController.php"
    name_prefix:  api_
    options:
        expose: true